# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ZYTD.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(294, 623)
        MainWindow.setMinimumSize(QtCore.QSize(294, 623))
        MainWindow.setMaximumSize(QtCore.QSize(294, 623))
        font = QtGui.QFont()
        font.setFamily("Qanelas ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("\n"
"<RCC warning=\"WARNING! File created programmatically. All changes made in this file will be lost!\">\n"
"  <qresource prefix=\"qss_icons/dark\">\n"
"    <file>rc/arrow_down.png</file>\n"
"    <file>rc/arrow_down@2x.png</file>\n"
"    <file>rc/arrow_down_disabled.png</file>\n"
"    <file>rc/arrow_down_disabled@2x.png</file>\n"
"    <file>rc/arrow_down_focus.png</file>\n"
"    <file>rc/arrow_down_focus@2x.png</file>\n"
"    <file>rc/arrow_down_pressed.png</file>\n"
"    <file>rc/arrow_down_pressed@2x.png</file>\n"
"    <file>rc/arrow_left.png</file>\n"
"    <file>rc/arrow_left@2x.png</file>\n"
"    <file>rc/arrow_left_disabled.png</file>\n"
"    <file>rc/arrow_left_disabled@2x.png</file>\n"
"    <file>rc/arrow_left_focus.png</file>\n"
"    <file>rc/arrow_left_focus@2x.png</file>\n"
"    <file>rc/arrow_left_pressed.png</file>\n"
"    <file>rc/arrow_left_pressed@2x.png</file>\n"
"    <file>rc/arrow_right.png</file>\n"
"    <file>rc/arrow_right@2x.png</file>\n"
"    <file>rc/arrow_right_disabled.png</file>\n"
"    <file>rc/arrow_right_disabled@2x.png</file>\n"
"    <file>rc/arrow_right_focus.png</file>\n"
"    <file>rc/arrow_right_focus@2x.png</file>\n"
"    <file>rc/arrow_right_pressed.png</file>\n"
"    <file>rc/arrow_right_pressed@2x.png</file>\n"
"    <file>rc/arrow_up.png</file>\n"
"    <file>rc/arrow_up@2x.png</file>\n"
"    <file>rc/arrow_up_disabled.png</file>\n"
"    <file>rc/arrow_up_disabled@2x.png</file>\n"
"    <file>rc/arrow_up_focus.png</file>\n"
"    <file>rc/arrow_up_focus@2x.png</file>\n"
"    <file>rc/arrow_up_pressed.png</file>\n"
"    <file>rc/arrow_up_pressed@2x.png</file>\n"
"    <file>rc/base_icon.png</file>\n"
"    <file>rc/base_icon@2x.png</file>\n"
"    <file>rc/base_icon_disabled.png</file>\n"
"    <file>rc/base_icon_disabled@2x.png</file>\n"
"    <file>rc/base_icon_focus.png</file>\n"
"    <file>rc/base_icon_focus@2x.png</file>\n"
"    <file>rc/base_icon_pressed.png</file>\n"
"    <file>rc/base_icon_pressed@2x.png</file>\n"
"    <file>rc/branch_closed.png</file>\n"
"    <file>rc/branch_closed@2x.png</file>\n"
"    <file>rc/branch_closed_disabled.png</file>\n"
"    <file>rc/branch_closed_disabled@2x.png</file>\n"
"    <file>rc/branch_closed_focus.png</file>\n"
"    <file>rc/branch_closed_focus@2x.png</file>\n"
"    <file>rc/branch_closed_pressed.png</file>\n"
"    <file>rc/branch_closed_pressed@2x.png</file>\n"
"    <file>rc/branch_end.png</file>\n"
"    <file>rc/branch_end@2x.png</file>\n"
"    <file>rc/branch_end_disabled.png</file>\n"
"    <file>rc/branch_end_disabled@2x.png</file>\n"
"    <file>rc/branch_end_focus.png</file>\n"
"    <file>rc/branch_end_focus@2x.png</file>\n"
"    <file>rc/branch_end_pressed.png</file>\n"
"    <file>rc/branch_end_pressed@2x.png</file>\n"
"    <file>rc/branch_line.png</file>\n"
"    <file>rc/branch_line@2x.png</file>\n"
"    <file>rc/branch_line_disabled.png</file>\n"
"    <file>rc/branch_line_disabled@2x.png</file>\n"
"    <file>rc/branch_line_focus.png</file>\n"
"    <file>rc/branch_line_focus@2x.png</file>\n"
"    <file>rc/branch_line_pressed.png</file>\n"
"    <file>rc/branch_line_pressed@2x.png</file>\n"
"    <file>rc/branch_more.png</file>\n"
"    <file>rc/branch_more@2x.png</file>\n"
"    <file>rc/branch_more_disabled.png</file>\n"
"    <file>rc/branch_more_disabled@2x.png</file>\n"
"    <file>rc/branch_more_focus.png</file>\n"
"    <file>rc/branch_more_focus@2x.png</file>\n"
"    <file>rc/branch_more_pressed.png</file>\n"
"    <file>rc/branch_more_pressed@2x.png</file>\n"
"    <file>rc/branch_open.png</file>\n"
"    <file>rc/branch_open@2x.png</file>\n"
"    <file>rc/branch_open_disabled.png</file>\n"
"    <file>rc/branch_open_disabled@2x.png</file>\n"
"    <file>rc/branch_open_focus.png</file>\n"
"    <file>rc/branch_open_focus@2x.png</file>\n"
"    <file>rc/branch_open_pressed.png</file>\n"
"    <file>rc/branch_open_pressed@2x.png</file>\n"
"    <file>rc/checkbox_checked.png</file>\n"
"    <file>rc/checkbox_checked@2x.png</file>\n"
"    <file>rc/checkbox_checked_disabled.png</file>\n"
"    <file>rc/checkbox_checked_disabled@2x.png</file>\n"
"    <file>rc/checkbox_checked_focus.png</file>\n"
"    <file>rc/checkbox_checked_focus@2x.png</file>\n"
"    <file>rc/checkbox_checked_pressed.png</file>\n"
"    <file>rc/checkbox_checked_pressed@2x.png</file>\n"
"    <file>rc/checkbox_indeterminate.png</file>\n"
"    <file>rc/checkbox_indeterminate@2x.png</file>\n"
"    <file>rc/checkbox_indeterminate_disabled.png</file>\n"
"    <file>rc/checkbox_indeterminate_disabled@2x.png</file>\n"
"    <file>rc/checkbox_indeterminate_focus.png</file>\n"
"    <file>rc/checkbox_indeterminate_focus@2x.png</file>\n"
"    <file>rc/checkbox_indeterminate_pressed.png</file>\n"
"    <file>rc/checkbox_indeterminate_pressed@2x.png</file>\n"
"    <file>rc/checkbox_unchecked.png</file>\n"
"    <file>rc/checkbox_unchecked@2x.png</file>\n"
"    <file>rc/checkbox_unchecked_disabled.png</file>\n"
"    <file>rc/checkbox_unchecked_disabled@2x.png</file>\n"
"    <file>rc/checkbox_unchecked_focus.png</file>\n"
"    <file>rc/checkbox_unchecked_focus@2x.png</file>\n"
"    <file>rc/checkbox_unchecked_pressed.png</file>\n"
"    <file>rc/checkbox_unchecked_pressed@2x.png</file>\n"
"    <file>rc/line_horizontal.png</file>\n"
"    <file>rc/line_horizontal@2x.png</file>\n"
"    <file>rc/line_horizontal_disabled.png</file>\n"
"    <file>rc/line_horizontal_disabled@2x.png</file>\n"
"    <file>rc/line_horizontal_focus.png</file>\n"
"    <file>rc/line_horizontal_focus@2x.png</file>\n"
"    <file>rc/line_horizontal_pressed.png</file>\n"
"    <file>rc/line_horizontal_pressed@2x.png</file>\n"
"    <file>rc/line_vertical.png</file>\n"
"    <file>rc/line_vertical@2x.png</file>\n"
"    <file>rc/line_vertical_disabled.png</file>\n"
"    <file>rc/line_vertical_disabled@2x.png</file>\n"
"    <file>rc/line_vertical_focus.png</file>\n"
"    <file>rc/line_vertical_focus@2x.png</file>\n"
"    <file>rc/line_vertical_pressed.png</file>\n"
"    <file>rc/line_vertical_pressed@2x.png</file>\n"
"    <file>rc/radio_checked.png</file>\n"
"    <file>rc/radio_checked@2x.png</file>\n"
"    <file>rc/radio_checked_disabled.png</file>\n"
"    <file>rc/radio_checked_disabled@2x.png</file>\n"
"    <file>rc/radio_checked_focus.png</file>\n"
"    <file>rc/radio_checked_focus@2x.png</file>\n"
"    <file>rc/radio_checked_pressed.png</file>\n"
"    <file>rc/radio_checked_pressed@2x.png</file>\n"
"    <file>rc/radio_unchecked.png</file>\n"
"    <file>rc/radio_unchecked@2x.png</file>\n"
"    <file>rc/radio_unchecked_disabled.png</file>\n"
"    <file>rc/radio_unchecked_disabled@2x.png</file>\n"
"    <file>rc/radio_unchecked_focus.png</file>\n"
"    <file>rc/radio_unchecked_focus@2x.png</file>\n"
"    <file>rc/radio_unchecked_pressed.png</file>\n"
"    <file>rc/radio_unchecked_pressed@2x.png</file>\n"
"    <file>rc/toolbar_move_horizontal.png</file>\n"
"    <file>rc/toolbar_move_horizontal@2x.png</file>\n"
"    <file>rc/toolbar_move_horizontal_disabled.png</file>\n"
"    <file>rc/toolbar_move_horizontal_disabled@2x.png</file>\n"
"    <file>rc/toolbar_move_horizontal_focus.png</file>\n"
"    <file>rc/toolbar_move_horizontal_focus@2x.png</file>\n"
"    <file>rc/toolbar_move_horizontal_pressed.png</file>\n"
"    <file>rc/toolbar_move_horizontal_pressed@2x.png</file>\n"
"    <file>rc/toolbar_move_vertical.png</file>\n"
"    <file>rc/toolbar_move_vertical@2x.png</file>\n"
"    <file>rc/toolbar_move_vertical_disabled.png</file>\n"
"    <file>rc/toolbar_move_vertical_disabled@2x.png</file>\n"
"    <file>rc/toolbar_move_vertical_focus.png</file>\n"
"    <file>rc/toolbar_move_vertical_focus@2x.png</file>\n"
"    <file>rc/toolbar_move_vertical_pressed.png</file>\n"
"    <file>rc/toolbar_move_vertical_pressed@2x.png</file>\n"
"    <file>rc/toolbar_separator_horizontal.png</file>\n"
"    <file>rc/toolbar_separator_horizontal@2x.png</file>\n"
"    <file>rc/toolbar_separator_horizontal_disabled.png</file>\n"
"    <file>rc/toolbar_separator_horizontal_disabled@2x.png</file>\n"
"    <file>rc/toolbar_separator_horizontal_focus.png</file>\n"
"    <file>rc/toolbar_separator_horizontal_focus@2x.png</file>\n"
"    <file>rc/toolbar_separator_horizontal_pressed.png</file>\n"
"    <file>rc/toolbar_separator_horizontal_pressed@2x.png</file>\n"
"    <file>rc/toolbar_separator_vertical.png</file>\n"
"    <file>rc/toolbar_separator_vertical@2x.png</file>\n"
"    <file>rc/toolbar_separator_vertical_disabled.png</file>\n"
"    <file>rc/toolbar_separator_vertical_disabled@2x.png</file>\n"
"    <file>rc/toolbar_separator_vertical_focus.png</file>\n"
"    <file>rc/toolbar_separator_vertical_focus@2x.png</file>\n"
"    <file>rc/toolbar_separator_vertical_pressed.png</file>\n"
"    <file>rc/toolbar_separator_vertical_pressed@2x.png</file>\n"
"    <file>rc/transparent.png</file>\n"
"    <file>rc/transparent@2x.png</file>\n"
"    <file>rc/transparent_disabled.png</file>\n"
"    <file>rc/transparent_disabled@2x.png</file>\n"
"    <file>rc/transparent_focus.png</file>\n"
"    <file>rc/transparent_focus@2x.png</file>\n"
"    <file>rc/transparent_pressed.png</file>\n"
"    <file>rc/transparent_pressed@2x.png</file>\n"
"    <file>rc/window_close.png</file>\n"
"    <file>rc/window_close@2x.png</file>\n"
"    <file>rc/window_close_disabled.png</file>\n"
"    <file>rc/window_close_disabled@2x.png</file>\n"
"    <file>rc/window_close_focus.png</file>\n"
"    <file>rc/window_close_focus@2x.png</file>\n"
"    <file>rc/window_close_pressed.png</file>\n"
"    <file>rc/window_close_pressed@2x.png</file>\n"
"    <file>rc/window_grip.png</file>\n"
"    <file>rc/window_grip@2x.png</file>\n"
"    <file>rc/window_grip_disabled.png</file>\n"
"    <file>rc/window_grip_disabled@2x.png</file>\n"
"    <file>rc/window_grip_focus.png</file>\n"
"    <file>rc/window_grip_focus@2x.png</file>\n"
"    <file>rc/window_grip_pressed.png</file>\n"
"    <file>rc/window_grip_pressed@2x.png</file>\n"
"    <file>rc/window_minimize.png</file>\n"
"    <file>rc/window_minimize@2x.png</file>\n"
"    <file>rc/window_minimize_disabled.png</file>\n"
"    <file>rc/window_minimize_disabled@2x.png</file>\n"
"    <file>rc/window_minimize_focus.png</file>\n"
"    <file>rc/window_minimize_focus@2x.png</file>\n"
"    <file>rc/window_minimize_pressed.png</file>\n"
"    <file>rc/window_minimize_pressed@2x.png</file>\n"
"    <file>rc/window_undock.png</file>\n"
"    <file>rc/window_undock@2x.png</file>\n"
"    <file>rc/window_undock_disabled.png</file>\n"
"    <file>rc/window_undock_disabled@2x.png</file>\n"
"    <file>rc/window_undock_focus.png</file>\n"
"    <file>rc/window_undock_focus@2x.png</file>\n"
"    <file>rc/window_undock_pressed.png</file>\n"
"    <file>rc/window_undock_pressed@2x.png</file>\n"
"  </qresource>\n"
"  <qresource prefix=\"qdarkstyle/dark\">\n"
"      <file>darkstyle.qss</file>\n"
"  </qresource>\n"
"</RCC>\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-11, -1, 501, 661))
        self.frame.setStyleSheet("QFrame {\n"
"\n"
"    background-color: rgb(179, 179, 179);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 30, 221, 31))
        self.label.setStyleSheet("QLabel {\n"
"    font: 81 20pt \"Qanelas ExtraBold\";\n"
"    \n"
"    color: rgb(242, 90, 58);\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 121, 21))
        self.label_2.setStyleSheet("QLabel {\n"
"    color: rgb(250, 143, 145);\n"
"    font: 81 10pt \"Qanelas ExtraBold\";\n"
"    \n"
"    color: rgb(242, 90, 58);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 121, 21))
        self.label_3.setStyleSheet("QLabel {\n"
"    color: rgb(250, 143, 145);\n"
"    font: 81 10pt \"Qanelas ExtraBold\";\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(20, 160, 281, 20))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    border-color: rgb(47, 47, 42);\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(30, 190, 91, 21))
        self.label_4.setStyleSheet("QLabel {\n"
"    color: rgb(250, 143, 145);\n"
"    font: 81 10pt \"Qanelas ExtraBold\";\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 220, 221, 20))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    border-color: rgb(47, 47, 42);\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(100, 570, 91, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    background-color: rgb(244, 244, 244);\n"
"}\n"
"QPushButton::hover{\n"
"border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    background-color: rgb(217, 217, 217);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    background-color: rgb(217, 217, 217);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(110, 280, 101, 31))
        self.label_5.setStyleSheet("QLabel {\n"
"    color: rgb(250, 143, 145);\n"
"    font: 81 12pt \"Qanelas ExtraBold\";\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 360, 131, 20))
        self.label_6.setStyleSheet("QLabel {\n"
"    color: rgb(250, 143, 145);\n"
"    font: 81 12pt \"Qanelas ExtraBold\";\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 220, 51, 20))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    background-color: rgb(244, 244, 244);\n"
"}\n"
"QPushButton::hover{\n"
"border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    background-color: rgb(217, 217, 217);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    background-color: rgb(217, 217, 217);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(140, 410, 47, 13))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(20, 380, 211, 22))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(100, 250, 121, 16))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.video = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.video.setStyleSheet("QRadioButton::indicator::unchecked {\n"
"     border-width: 2px;\n"
"     border-style: solid;\n"
"     border-color: black;\n"
"    border-radius:4px\n"
" }\n"
"QRadioButton::indicator::checked {\n"
"    \n"
"    background-color: rgb(47, 47, 42);\n"
"     border-width: 2px;\n"
"     border-style: solid;\n"
"     border-radius:4px;\n"
"     border-color: black;\n"
" }\n"
"")
        self.video.setObjectName("video")
        self.horizontalLayout_3.addWidget(self.video)
        self.playlist = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.playlist.setStyleSheet("QRadioButton::indicator::unchecked {\n"
"    font: 81 8pt \"Qanelas ExtraBold\";\n"
"     border-width: 2px;\n"
"     border-style: solid;\n"
"     border-color: black;\n"
"    border-radius:4px\n"
" }\n"
"QRadioButton::indicator::checked {\n"
"    \n"
"    background-color: rgb(47, 47, 42);\n"
"     border-width: 2px;\n"
"     border-style: solid;\n"
"     border-radius:4px;\n"
"     border-color: black;\n"
" }\n"
"")
        self.playlist.setObjectName("playlist")
        self.horizontalLayout_3.addWidget(self.playlist)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 380, 51, 23))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    background-color: rgb(244, 244, 244);\n"
"}\n"
"QPushButton::hover{\n"
"border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    background-color: rgb(217, 217, 217);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"    border-style:solid;\n"
"    background-color: rgb(217, 217, 217);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 310, 101, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.audio = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.audio.setStyleSheet("QRadioButton::indicator::unchecked {\n"
"     border-width: 2px;\n"
"     border-style: solid;\n"
"     border-color: black;\n"
"    border-radius:4px\n"
" }\n"
"QRadioButton::indicator::checked {\n"
"    \n"
"    background-color: rgb(47, 47, 42);\n"
"     border-width: 2px;\n"
"     border-style: solid;\n"
"     border-radius:4px;\n"
"     border-color: black;\n"
" }\n"
"")
        self.audio.setObjectName("audio")
        self.horizontalLayout.addWidget(self.audio)
        self.mp4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.mp4.setStyleSheet("QRadioButton::indicator::unchecked {\n"
"     border-width: 2px;\n"
"     border-style: solid;\n"
"     border-color: black;\n"
"    border-radius:4px\n"
" }\n"
"QRadioButton::indicator::checked {\n"
"    \n"
"    background-color: rgb(47, 47, 42);\n"
"     border-width: 2px;\n"
"     border-style: solid;\n"
"     border-radius:4px;\n"
"     border-color: black;\n"
" }\n"
"")
        self.mp4.setObjectName("mp4")
        self.horizontalLayout.addWidget(self.mp4)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(20, 420, 221, 21))
        self.label_9.setStyleSheet("QLabel {\n"
"    color: rgb(250, 143, 145);\n"
"    font: 81 12pt \"Qanelas ExtraBold\";\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(30, 480, 261, 21))
        self.label_8.setStyleSheet("QLabel {\n"
"    color: rgb(250, 143, 145);\n"
"    font: 9pt \"Roboto\";\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZYT Downloader"))
        self.label.setText(_translate("MainWindow", "ZYT Downlaoder!"))
        self.label_2.setText(_translate("MainWindow", "By zeyad elkholy"))
        self.label_3.setText(_translate("MainWindow", "Enter The URL Link :"))
        self.label_4.setText(_translate("MainWindow", "Enter The Path :"))
        self.pushButton.setText(_translate("MainWindow", "downlaod"))
        self.label_5.setText(_translate("MainWindow", "select format :"))
        self.label_6.setText(_translate("MainWindow", "select resolution :"))
        self.pushButton_2.setText(_translate("MainWindow", "select"))
        self.video.setText(_translate("MainWindow", "video"))
        self.playlist.setText(_translate("MainWindow", "playlist"))
        self.pushButton_3.setText(_translate("MainWindow", "search"))
        self.audio.setText(_translate("MainWindow", "mp3"))
        self.mp4.setText(_translate("MainWindow", "mp4"))

